services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order-api-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=portfolio-mysql
      - DB_PORT=3306
      - DB_DATABASE=mit503_laravel_demo
      - DB_USERNAME=portfolio_user
      - DB_PASSWORD=Qw3rtyu!
      - QUEUE_CONNECTION=database
      - WEBHOOK_URL=http://localhost:8000/api/v1/webhook-test
    networks:
      - portfolio-network

networks:
  portfolio-network:
    external: true
    name: portfolio_portfolio-network
